project:
  type: website
  output-dir: .

website:
  title: "eMOLT"
  favicon: images/eMOLT_Logo.jpg
  navbar: 
    left:
      - href: about.qmd
        text: About
      - href: signup.qmd
        text: Sign Up
      - href: scipubs.qmd
        text: Scientific Publications
      - href: media.qmd
        text: Media
      - href: partnerships.qmd
        text: Partnerships
      - href: data.qmd
        text: Data Access
    right: 
      - href: https://gomlf.org/emolt
        text: "![](images/gomlf.png){height=100px}"
      - href: https://www.fisheries.noaa.gov/new-england-mid-atlantic/climate-change/partnering-fishing-industry-monitor-northeast-shelf
        text: "![](images/crb.png){height=100px}"
  page-footer:
    left: 
      - text: Find us on LinkedIn
      - icon: linkedin
        href: https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7258203580950630400
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    email-obfuscation: none

editor: visual

