project:
  type: website

website:
  title: "eMOLT"
  navbar: 
    left:
      - href: about.qmd
        text: About
      - href: signup.qmd
        text: Sign Up
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    email-obfuscation: none

editor: visual

