---
title: "Media Mentions"
---

### 2026

- [NOAA Fisheries: Righting the Course of Distrust Through Collaboration](https://www.fisheries.noaa.gov/feature-story/righting-course-distrust-through-collaboration)
- [MVTimes.com: Feds cut global ocean-observing network](https://www.mvtimes.com/2026/06/11/feds-cut-global-ocean-observing-network/)
- [CapeCodNews.org: Got Data? These Fishing Vessels Do!](https://capecodnews.org/connecting-data-dots-between-fishermen-and-scientists/)
- [New York Times: In New England, Catching Climate Data Along With Fish](https://www.nytimes.com/2026/04/01/climate/new-england-fishermen-ocean-data.html)
- [NOAA Fisheries: Scientists and the Fishing Industry Join Forces for Better Data and Management (Part 1)](https://www.fisheries.noaa.gov/feature-story/scientists-and-fishing-industry-join-forces-better-data-and-management-part-1)

### 2025

- [WBUR: In New England, climate change is moving fast. The fishing industry is not](https://www.wbur.org/news/2025/01/15/climate-change-new-england-fishery-regulations)
- [Cape Cod Times: 'Alarm bells.' After low oxygen scare in Cape waters, Falmouth company uses $2M to help](https://www.capecodtimes.com/story/business/manufacturing/2025/03/02/lowell-instruments-falmouth-ocean-sensors-water-temperature-oxygen-levels-bottom/78463218007/)
- [Marine Biological Laboratory: R/V Gemma Gains New Environmental Sensor](https://www.mbl.edu/news/gemma-gains-new-environmental-sensor)

### 2024

- [CapeCod.com: State Provides Millions for Cape Coastal Resilience](https://www.capecod.com/newscenter/state-provides-millions-for-cape-coastal-resilience/)
- [Cape Cod Commercial Fishermen's Alliance: Two million dollar grant to help research, commercial fishermen](https://capecodfishermen.org/two-million-dollar-grant-to-help-research-commercial-fishermen/)
- [Provincetown Independent: $2M Grant to Fishermen's Alliance Means More Boats Gathering Ocean Data](https://provincetownindependent.org/local-journalism-project/next-generation/2024/12/04/2m-grant-to-fishermens-alliance-means-more-boats-gathering-ocean-data/)

### 2022

- [Cape Cod Commercial Fishermen's Alliance: Manning and Maynard Push Fishermen Science Forward](https://capecodfishermen.org/manning-and-maynard-push-fishermen-science-forward/)

### 2021

- [National Science Foundation: Example of an Integrated Ocean Observing System](https://oceanobservatories.org/2021/10/example-of-integrated-ocean-observing-system/)
- [Cape Cod Commercial Fishermen's Alliance: Sustainability Depends on Science](https://capecodfishermen.org/sustainability-depends-on-science/)

### 2020 and earlier

- [Fishermen's Voice: eMOLT and Other Ocean Monitoring Projects Underway](https://www.fishermensvoice.com/archives/202004EMOLTAndOtherOceanMonitoringProjectsAreUnderway.html)
- [NOAA Fisheries: Low-Cost Technology Helps Connect Fishermen and Students to Science](https://www.fisheries.noaa.gov/feature-story/low-cost-technology-helps-connect-fishermen-and-students-science)
- [Accuweather: Citizen scientists on the seaboard, How lobstermen gather data from the bottom of the ocean](https://www.accuweather.com/en/weather-news/citizen-scientists-on-the-seaboard-how-lobstermen-gather-data-from-the-bottom-of-the-ocean/70002099)
- [NOAA Fisheries: Fisherman's Perspective: Using Electronic Reporting Devices to Provide Real Time Data and Further Understand Ocean Ecosystem](https://www.fisheries.noaa.gov/feature-story/fishermans-perspective-using-electronic-reporting-devices-provide-real-time-data-and)
- [Environment Coastal and Offshore Magazine: Adventures in Citizen Science](https://ecomagazine.com/in-depth/adventures-in-citizen-science/)
- [ABC News: New England lobster traps are nabbing dinner, data](https://abcnews.com/Technology/story?id=7168914&page=1)
- [Fishermen's Voice: Lobster Traps and Drifters Monitoring the Sea](https://www.fishermensvoice.com/archives/201407Index.html)
- [National Science Foundation: Scientists Uncover Diversion of Gulf Stream Path in Late 2011](https://oceanobservatories.org/2012/10/scientists-uncover-diversion-of-gulf-stream-path-in-late-2011/)